
#' ---
#' title: "Redlining"
#' author: A. Justin Kirkpatrick
#' output:
#'   pdf_document:
#'     keep_tex: true
#'     extra_dependencies: ["bbm", "threeparttable","float","booktabs"]
#' ---
#'
#' This is a report generated by `knitr::spin()`
#'

#+ echo=FALSE, warning=FALSE, error=FALSE, message=FALSE

########
## Analysis for Redlining
########
c("#FFFFFF", "#FFFFFF", "#FFFFFF")
require(rgdal)
require(rgeos)
require(sp)
require(sf)
require(stargazer)
library(viridis)
library(rvest)
require(tidycensus)
require(sp)
require(rgdal)
require(raster)
require(tigris)
require(snow)
require(doSNOW)
require(parallel)
require(foreach)
require(iterators)
require(fixest)
require(modelsummary)
require(gtable)
require(knitr)
require(kableExtra)
options(tigris_use_cache = TRUE)
# numCores = 2
# 
# if(NROW(showConnections())!=numCores){ # faster core construction
#   if(NROW(showConnections())>0) stopCluster(cl)
#   cl <- parallel::makeCluster(rep('localhost',numCores), type='PSOCK')
#   registerDoSNOW(cl)}





#' # Introduction
#' This is the section with the introduction
#' 
#' # Data
#' This is the section with the data. 
#' And the section where we process the data




#+ process-1, echo=FALSE, cache = T, warning=F, message=F
    # Load files --------------------------------------------------------------
    WORK.OUT = file.path(BASE,'ajk41/Low Income Energy/Data/OUTPUT',Sys.Date())
    dir.create(WORK.OUT, recursive=T)
    
    Processed_HOLC = file.path(BASE, 'ajk41/Low Income Energy/Data/Zillow/Processed_HOLC')
    
    # mykey = "ff90006e6d5f1960ef3bbb37579766bb563b1121"
    # census_api_key(mykey, install=T)
    
    BGZ = readRDS(jLoad(WORK.OUT, 'BG_ZCTA_HOLC_int'))
    BG.int.full = BGZ[[1]]
    ZCTA.int.full = BGZ[[2]]
    HOLC = BGZ[[3]] # readRDS(jLoad(WORK.OUT, 'HOLC_with_data')) # 10-12
    
    # Dissolve to BG with data on share in each GRADE ---------
    # Summarize (dissolve) BG and ZCTAs and average HOLC-data within.
    #         - Hopefully a reasonable number of ~100% in A,B,C,or D.
    BG.int = BG.int.full %>% 
      group_by_at(vars(AFFGEOID, TRACTCE, BLKGRPCE, UtilityGas:TotalRace)) %>%
      summarize(NBlack_YN = max(NBlack_YN), NBlack_PCT = weighted.mean(as.numeric(NBlack_PCT), w = segmentArea),
                Rent35_Mean = weighted.mean(Rent35_Mean, w=segmentArea), Rent3739_Mean = weighted.mean(Rent3739_Mean, w = segmentArea), 
                Minc = weighted.mean(Minc, w=segmentArea),
                GRADE.A = sum(segmentArea[GRADE=='A'])/sum(segmentArea),
                GRADE.B = sum(segmentArea[GRADE=='B'])/sum(segmentArea),
                GRADE.C = sum(segmentArea[GRADE=='C'])/sum(segmentArea),
                GRADE.D = sum(segmentArea[GRADE=='D'])/sum(segmentArea),
                GRADE.NA = sum(segmentArea[is.na(GRADE)])/sum(segmentArea),
                GRADE.max = factor(GRADE[which.max(segmentArea)]),
                share.max = max(segmentArea)/sum(segmentArea)) %>% # Note: check that no AFFGEOID are duplicated
      dplyr::mutate(STATEFP = gsub(pattern = '.*US([0-9]{2})([0-9]{3}).*', '\\1', x=AFFGEOID),
                    COUNTYFP = gsub(pattern = '.*US([0-9]{2})([0-9]{3}).*', '\\2', x=AFFGEOID),
                    STCO =     gsub(pattern = '.*US([0-9]{5}).*', '\\1', x=AFFGEOID)) %>%
      dplyr::mutate(isD = GRADE.D>.8,
                    GRADE.max = relevel(GRADE.max, ref = 'C'))
    
    
    ZCTA.int = ZCTA.int.full %>% 
      group_by_at(vars(AFFGEOID10, NAME.zip, UtilityGas:TotalRace)) %>%
      summarize(NBlack_YN = max(NBlack_YN), NBlack_PCT = weighted.mean(as.numeric(NBlack_PCT), w = segmentArea),
                Rent35_Mean = weighted.mean(Rent35_Mean, w=segmentArea), Rent3739_Mean = weighted.mean(Rent3739_Mean, w = segmentArea), 
                Minc = weighted.mean(Minc, w=segmentArea),
                GRADE.A = sum(segmentArea[GRADE=='A'])/sum(segmentArea),
                GRADE.B = sum(segmentArea[GRADE=='B'])/sum(segmentArea),
                GRADE.C = sum(segmentArea[GRADE=='C'])/sum(segmentArea),
                GRADE.D = sum(segmentArea[GRADE=='D'])/sum(segmentArea),
                GRADE.NA = sum(segmentArea[is.na(GRADE)])/sum(segmentArea),
                GRADE.max = factor(GRADE[which.max(segmentArea)], levels=c('C','D','B','A',NA)),
                share.max = max(segmentArea)/sum(segmentArea)) %>% # Note: check that no AFFGEOID are duplicated %>%
      st_join(counties(cb=TRUE) %>% dplyr::select(STCO = GEOID) %>% st_transform(st_crs(HOLC))) %>%
      dplyr::mutate(isD = GRADE.D>.8)
    
    # stopifnot(sum(duplicated(ZCTA.int$AFFGEOID10))==0)
    stopifnot(sum(duplicated(BG.int$AFFGEOID))==0)

    # end----
#' 
#' 
#' 
#' This is the text. $f = \frac{b}{c}$.
#' 
#+ echo=FALSE, fig.width=7, result='as.is'
# New 10-13-20:
# Using shraes of each BG and ZCTA that are D/C/B/A
# simp1 = feols(fml = OtherSubstandard ~ poly(GRADE.D,2) + MedIncome2018 + Minc + Rent3739_Mean + NBlack_PCT | as.factor(STCO), 
#               data = BG.int %>% dplyr::filter(!is.na(GRADE.D)))
                           
simp2 = feols(fml = OtherSubstandard ~ isD + MedIncome2018 + Minc + Rent3739_Mean + NBlack_PCT | as.factor(STCO), 
              data = BG.int %>% dplyr::filter(!is.na(GRADE.D& !is.na(GRADE.max))))

simp3 = feols(fml = OtherSubstandard ~ as.factor(GRADE.max) + MedIncome2018*Minc + Rent3739_Mean | as.factor(STCO),
              data = BG.int %>% dplyr::filter(share.max>.8& !is.na(GRADE.max)))

simp4 = feols(fml = OtherSubstandard ~ as.factor(GRADE.max) +  MedIncome2018+Minc + Rent3739_Mean + NBlack_YN + NBlack_PCT + Black + White + Asian | as.factor(STCO), 
              data = BG.int %>% dplyr::filter(share.max>.8 & !is.na(GRADE.max)))


modelsummary(models = list(simp2, simp3, simp4), se = 'cluster',
             output = 'kableExtra',  # instead of latex so that I can use kable_styling(latex_options = 'scale_down') for the table
             stars=TRUE,
             notes = 'Robust SE clustered by FIPS county') %>%  # output as kableExtra
  kable_styling(latex_options = 'scale_down') # to use this kableExtra option!






/* rmarkdown::render(rstudioapi::getSourceEditorContext()$path)
*/


#' # End
#' 
###################
###################
###################


